<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends EntityRepository
{
    public function findAllClasses()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p.nom, p.prenom, per.idPersonne
                FROM AppBundle:Professeur p, AppBundle:Personne per WHERE per.idPersonne=p.idProfesseur
                
                ')
            ->getResult();
    }
}
