<?php

namespace AppBundle\Entity;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllClasses()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c.libelleClasse
            FROM AppBundle:Classe c, AppBundle:Pendant pe, AppBundle:Module m, AppBundle:Professeur p
            WHERE c.idClasse = pe.idClasse
            AND pe.idModule = m.idModule
                ')
            ->getResult();
    }
}
