<?php

namespace AppBundle\Entity;

/**
 * DerouleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DerouleRepository extends \Doctrine\ORM\EntityRepository
{
}
