<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DerouleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DerouleRepository extends EntityRepository
{
}
