<?php

namespace AppBundle\Entity;

/**
 * PendantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PendantRepository extends \Doctrine\ORM\EntityRepository
{
}
