<?php

namespace AppBundle\Entity;

/**
 * ProfesseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesseurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAbsences()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a.justificatif, a.motif
                FROM AppBundle:Absence a, AppBundle:Personne p WHERE a.idPersonne=p.idPersonne 
                
                ')
            ->getResult();
    }
}
