<?php

namespace AppBundle\Entity;

/**
 * SemestreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemestreRepository extends \Doctrine\ORM\EntityRepository
{
}
